### PR TITLE
Fix #113 - On login page, redirect to en.support.wordpress.com

### LINKED ISSUE #113: Help Menu on Login screen
The new help menu does not work if not logged in.

It requires being in Calypso, so does not work when used on the login screen. 
I suggest to update to trigger opening: https://en.support.wordpress.com/

### PR DESCRIPTION
**Pull request by mkaz**
The new help page within Calypso requires a user to be logged in, which
is obviously not the case when on the /login page. Adds check in Help
Menu if on /login to redirect to external support page.

### CODE REVIEW

File: desktop/lib/menu/help-menu.js [hunk 1]
```diff
@@ -30,8 +31,14 @@ module.exports = function( mainWindow ) {
 		{
 			label: 'How can we help?',
 			click: function() {
-				mainWindow.show();
-				ipc.showHelp( mainWindow );
+				// on login page - user logged out
+				let parsedURL = url.parse( mainWindow.webContents.getURL() );
+				if ( parsedURL.pathname === '/login' ) {
```
Comment (mjangda) [inline desktop/lib/menu/help-menu.js]: We have more routes now, with Sign Up in the app so this doesn't cover all cases. It would be better to check if the user is currently logged in, instead.

**Comment by mkaz** [comment]
@mjangda Agreed. Reworked to have a State module which can be used for logged in & out - and easily extendable when we want

File: desktop/lib/menu/help-menu.js [hunk 2]
```diff
@@ -5,12 +5,14 @@
  */
 const shell = require( 'electron' ).shell;
 const ipc = require( 'lib/calypso-commands' );
+const url = require( 'url' );
```
Comment (mjangda) [inline desktop/lib/menu/help-menu.js]: Can remove this now.

**Comment by mjangda** [comment]
Nice, one small thing and :ship:
