### PR TITLE
enhancement: print handler

### LINKED ISSUE #910: "Print codes" button for 2FA backup codes fails silently
#### Steps to reproduce
1. Activate 2FA
2. In the **Generate Backup Codes** stage, click Print Codes
3. Confirm that it fails silently

#### What I expected
Upon clicking Print codes, a prompt should appear.

#### What happened instead
Nothing happens on click.

#### App Version / OS version
6.0.0-beta2 / Mac OS 10.13

#### Screenshot / Video
https://cloudup.com/ciuGadMso39

#### Context / Source
Reported initially at https://wp.me/p5T066-1l3#comment-5074

#manual-testing #dogfooding

### PR DESCRIPTION
**Pull request by nsakaimbo**
### Description

This PR contains some minor tweaks to the print handler in the desktop app, discovered while debugging the "Print Recovery Codes" feature which was silently not working.

Works in conjunction with the changes in Automattic/wp-calypso#43523 (merged).

<p align="center">

</p>

Fixes #910 

### Description

When the "print recovery codes" button was selected, it would silently fail - no action and no error message displayed to the user. This action was [wired up in Calypso](https://github.com/Automattic/wp-calypso/pull/43523/files#diff-dd80c6b9bd20574564ee8c195e71d232L92) and looks like it used to work, but at some point silently broke (appears to be a CommonJS vs ES6 import/export misspecification). 

The root cause of the breakage has already been fixed in Automattic/wp-calypso#43523, but during the course of debugging I found some minor quality-of-life improvements for the desktop print handler (namely, adding some logging and explicitly specifying the charset).

### To Test

Download, extract and install an artifact from this PR (built with with Calypso SHA noted above: [link](https://app.circleci.com/pipelines/github/Automattic/wp-desktop/16967/workflows/0f468659-8f7b-4cf3-992e-cbf9f604696d/jobs/65456/artifacts)). From your profile, enable two-factor authentication and select the "Print Recovery Codes" button.

### CODE REVIEW

File: desktop/app-handlers/printer/index.js [hunk 1]
```diff
@@ -18,11 +16,17 @@ module.exports = function() {
 
 		log.debug( 'Printing HTML' );
 
-		printer.loadURL( 'data:text/html,' + encodeURIComponent( html ) );
+		const file = 'data:text/html;charset=UTF-8,' + encodeURIComponent( html );
+		printer.loadURL( file );
 
 		printer.webContents.on( 'dom-ready', function() {
+			const options = { silent: false }; // ask the user for print settings
```
Comment (nsakaimbo) [inline desktop/app-handlers/printer/index.js:23]: Note: this is the default but just wanted to make it explicit. Also, specifying the options explicitly allows us to use the `webContents.print` callback to log error messages.

**Review by dmsnell — APPROVED** [review]
Thanks for updating the description. I didn't test this and am relying on you doing that. Code looks fine!
